#!/usr/bin/env python3
# =========================================================================
# Semiannual Trustee Audit report in the layout of Form 1295 (Sprint 6N).
#
# Compiles a print-ready PDF from one Trustee audit desk (finance.getTrusteeAudit's TrusteeAuditWorkspace) with
# ReportLab. The web portal's server route (apps/web/app/api/finance/form-1295) writes the desk to a JSON file and runs
# this script; it can also be run by hand:
#
#   python scripts/form_1295_report.py --input audit.json [--output generated/Form_1295_Audit_Report.pdf]
#
# Input JSON: { "council": { "number": 15295, "name": "St. Jude Council" }, "workspace": { ...TrusteeAuditWorkspace },
#               "generatedAt": "2026-10-08 19:30:00" }
#
# The report is the council's own working copy. It carries no emblem and states plainly that it is not the official
# Supreme Council form. Requires: pip install -r scripts/requirements.txt (reportlab).
# =========================================================================
import argparse
import json
import sys
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = ROOT / 'generated' / 'Form_1295_Audit_Report.pdf'

DISCLAIMERS = [
    'This report was generated by the council tracking platform from the council\'s own general ledger. It is NOT an '
    'official Knights of Columbus Supreme Council form and does not replace Form 1295 as the Supreme Council '
    'prescribes and receives it. Copy its figures onto the official form and file that form as the Supreme Council directs.',
    'The figures are only as accurate as the ledger entries. Before signing, the Trustees must check every line against '
    'the original bank statements, the Financial Secretary\'s and Treasurer\'s records, and the supporting receipts.',
    'Cash means the council\'s ledger cash accounts (bank accounts and the goal funds set aside inside them). Equipment, '
    'receivables, unpaid bills and any account not kept in the ledger are not part of this reconciliation.',
    'An electronic signature recorded in the platform shows that the Trustee verified the lines on the audit desk. The '
    'official form, the council\'s bylaws or the Supreme Council may still require handwritten signatures.',
    'Confidential: this report contains council financial information. Share it only with the council\'s officers, '
    'Trustees and the Supreme Council.',
]

GOLD = colors.HexColor('#B8860B')


def money(value):
    value = float(value or 0)
    sign = '-' if value < 0 else ''
    return f'{sign}${abs(value):,.2f}'


def esc(text):
    return str(text if text is not None else '').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def load(path):
    data = json.loads(Path(path).read_text(encoding='utf-8'))
    ws = data.get('workspace')
    if not isinstance(ws, dict) or not isinstance(ws.get('lines'), list):
        raise ValueError('The input has no audit workspace with lines.')
    council = data.get('council') or {}
    return council, ws, str(data.get('generatedAt') or '')


def build(council, ws, generated_at, output):
    styles = getSampleStyleSheet()
    title = ParagraphStyle('T', parent=styles['Title'], fontSize=16, leading=20, spaceAfter=2)
    subtitle = ParagraphStyle('S', parent=styles['Normal'], alignment=TA_CENTER, fontSize=10, leading=13, textColor=colors.HexColor('#333333'))
    h2 = ParagraphStyle('H2', parent=styles['Heading2'], fontSize=12, leading=15, spaceBefore=10, spaceAfter=4)
    body = ParagraphStyle('B', parent=styles['Normal'], fontSize=9, leading=12)
    small = ParagraphStyle('Sm', parent=styles['Normal'], fontSize=7.5, leading=9.5)
    cell = ParagraphStyle('C', parent=styles['Normal'], fontSize=7.5, leading=9)
    banner = ParagraphStyle('Ban', parent=styles['Normal'], alignment=TA_CENTER, fontSize=11, leading=14, textColor=colors.white, fontName='Helvetica-Bold')

    locked = ws.get('status') == 'LOCKED'
    status_text = 'LOCKED - signed by the Trustees' if locked else 'DRAFT - NOT SIGNED: the period is not locked and its figures may still change'
    council_line = f"{esc(council.get('name') or 'Council')} (Council {esc(council.get('number') or '-')})"

    story = [
        Paragraph('Semiannual Audit Report of the Trustees', title),
        Paragraph('Prepared in the layout of Form 1295 · council working copy, not the official form', subtitle),
        Spacer(1, 8),
    ]
    status_table = Table([[Paragraph(esc(status_text), banner)]], colWidths=[7.0 * inch])
    status_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.black if locked else colors.HexColor('#7A1F1F')),
        ('BOX', (0, 0), (-1, -1), 3, GOLD),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    story += [status_table, Spacer(1, 8)]

    info = [
        ['Council', Paragraph(council_line, body)],
        ['Audit period', f"{ws.get('periodLabel', '')} ({ws.get('fromDate', '')} to {ws.get('throughDate', '')})"],
        ['Fraternal year', ws.get('fiscalYear', '')],
        ['Lines verified', f"{ws.get('verifiedCount', 0)} of {ws.get('lineCount', 0)}"],
        ['Locked at', (ws.get('audit') or {}).get('locked_at') or '-'],
        ['Report generated', generated_at or '-'],
    ]
    t = Table(info, colWidths=[1.6 * inch, 5.4 * inch])
    t.setStyle(TableStyle([
        ('FONT', (0, 0), (0, -1), 'Helvetica-Bold', 9),
        ('FONT', (1, 0), (1, -1), 'Helvetica', 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F2F2F2')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(t)

    story.append(Paragraph('1. Cash reconciliation', h2))
    recon = [
        ['Cash on hand at the beginning of the period', money(ws.get('cashBalanceBeginning'))],
        ['Add: receipts during the period', money(ws.get('receipts'))],
        ['Less: disbursements during the period', money(ws.get('disbursements'))],
        ['Cash on hand at the end of the period', money(ws.get('cashBalanceEnding'))],
        ['Difference (should be $0.00)', money(ws.get('difference'))],
    ]
    t = Table(recon, colWidths=[5.0 * inch, 2.0 * inch])
    t.setStyle(TableStyle([
        ('FONT', (0, 0), (-1, -1), 'Helvetica', 9.5),
        ('FONT', (0, 3), (-1, 3), 'Helvetica-Bold', 9.5),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('LINEABOVE', (0, 3), (-1, 3), 1.2, colors.black),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(t)
    accounts = ', '.join(
        f"{esc(a.get('accountName'))}{' (goal fund)' if a.get('isVirtualGoal') else ''}" for a in ws.get('cashAccounts') or []
    )
    story.append(Spacer(1, 4))
    story.append(Paragraph(f'Cash accounts in scope: {accounts or "none"}. Transfers between these accounts are listed below but '
                           'move no money in or out, so they are left out of receipts and disbursements.', small))

    story.append(Paragraph('2. Ledger lines verified against the bank statements', h2))
    rows = [['Date', 'Account', 'Description', 'Check #', 'Receipt', 'Disbursement', 'Verified', 'Verified by']]
    for line in ws.get('lines') or []:
        e = line.get('entry') or {}
        desc = esc(e.get('Description'))
        if line.get('transfer'):
            desc += ' <i>(transfer)</i>'
        rows.append([
            str(e.get('DateLogged') or '')[:10],
            Paragraph(esc(line.get('accountName')), cell),
            Paragraph(desc, cell),
            esc(e.get('CheckNumber') or ''),
            money(e.get('DebitAmount')) if float(e.get('DebitAmount') or 0) > 0 else '',
            money(e.get('CreditAmount')) if float(e.get('CreditAmount') or 0) > 0 else '',
            'Yes' if line.get('verified') else 'NO',
            Paragraph(esc(line.get('verifiedByName') or ''), cell),
        ])
    if len(rows) == 1:
        rows.append(['', '', Paragraph('No cash lines were posted in this period.', cell), '', '', '', '', ''])
    widths = [0.72, 1.05, 2.0, 0.55, 0.75, 0.82, 0.5, 0.86]
    t = Table(rows, colWidths=[w * inch for w in widths], repeatRows=1)
    style = [
        ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 7.5),
        ('FONT', (0, 1), (-1, -1), 'Helvetica', 7.5),
        ('BACKGROUND', (0, 0), (-1, 0), colors.black),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.4, colors.grey),
        ('ALIGN', (4, 1), (5, -1), 'RIGHT'),
        ('ALIGN', (6, 1), (6, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]
    for i, line in enumerate(ws.get('lines') or [], start=1):
        if not line.get('verified'):
            style.append(('FONT', (6, i), (6, i), 'Helvetica-Bold', 7.5))
            style.append(('TEXTCOLOR', (6, i), (6, i), colors.HexColor('#7A1F1F')))
    t.setStyle(TableStyle(style))
    story.append(t)

    story.append(Paragraph('3. Trustee signatures', h2))
    sigs = ws.get('signatures') or []
    sig_rows = [['Trustee', 'Seat', 'Signed electronically (UTC)']]
    for s in sigs:
        sig_rows.append([esc(s.get('name')), esc(s.get('role')), esc(s.get('signedAt'))])
    if not sigs:
        sig_rows.append(['No Trustee has signed this audit.', '', ''])
    t = Table(sig_rows, colWidths=[2.8 * inch, 1.4 * inch, 2.8 * inch])
    t.setStyle(TableStyle([
        ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 9),
        ('FONT', (0, 1), (-1, -1), 'Helvetica', 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#F2F2F2')),
    ]))
    story.append(t)
    story.append(Spacer(1, 10))
    wet_table = Table([['_' * 48, '_' * 20] for _ in range(3)] + [['Trustee signature', 'Date']], colWidths=[4.6 * inch, 2.4 * inch])
    wet_table.setStyle(TableStyle([('FONT', (0, 0), (-1, -1), 'Helvetica', 8), ('TOPPADDING', (0, 0), (-1, -1), 10)]))
    story.append(KeepTogether([Paragraph('Handwritten signatures, where the official form or the bylaws require them:', small), wet_table]))

    story.append(Paragraph('Disclaimers', h2))
    for i, text in enumerate(DISCLAIMERS, start=1):
        story.append(Paragraph(f'{i}. {esc(text)}', small))
        story.append(Spacer(1, 2))

    def footer(canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 7)
        canvas.drawString(0.75 * inch, 0.5 * inch, f"{council.get('name') or 'Council'} · {ws.get('periodLabel', '')} Trustee audit · not an official Supreme Council form")
        canvas.drawRightString(7.75 * inch, 0.5 * inch, f'Page {doc.page}')
        if not locked:
            canvas.setFont('Helvetica-Bold', 60)
            canvas.setFillColor(colors.Color(0.6, 0.1, 0.1, alpha=0.12))
            canvas.translate(4.25 * inch, 5.5 * inch)
            canvas.rotate(35)
            canvas.drawCentredString(0, 0, 'DRAFT')
        canvas.restoreState()

    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    doc = SimpleDocTemplate(
        str(output),
        pagesize=LETTER,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.7 * inch,
        bottomMargin=0.8 * inch,
        title=f"Trustee Audit {ws.get('periodLabel', '')}",
        author=str(council.get('name') or 'Council'),
        subject='Semiannual Trustee audit (Form 1295 layout, council working copy)',
    )
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return output


def main(argv=None):
    parser = argparse.ArgumentParser(description='Compile the Semiannual Trustee Audit report (Form 1295 layout) as a PDF.')
    parser.add_argument('--input', required=True, help='JSON file with council, workspace and generatedAt')
    parser.add_argument('--output', default=str(DEFAULT_OUTPUT), help='PDF path (default: generated/Form_1295_Audit_Report.pdf)')
    args = parser.parse_args(argv)
    try:
        council, ws, generated_at = load(args.input)
        out = build(council, ws, generated_at, args.output)
    except Exception as err:  # noqa: BLE001 - report any failure to the calling route on stderr
        print(f'form_1295_report: {err}', file=sys.stderr)
        return 1
    print(out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
