// Placeholder for the production driver.
//
// React Native cannot open a TDS connection to Azure SQL directly, so the real
// driver will most likely be an HTTPS client for an API (Azure Functions, or the
// Next.js route handlers in apps/web) that owns the Azure SQL connection.
// Implement each method below, then set EXPO_PUBLIC_DATA_DRIVER=remote.
// No UI code changes: views only ever see the DataService contract.
import type { DataService } from '@kofc/shared';

const notImplemented = (method: string) => async (): Promise<never> => {
  throw new Error(`RemoteDataService.${method} is not implemented yet (production Azure SQL driver).`);
};

/** Written out explicitly so the compiler flags this file whenever the contract gains a method. */
export function createRemoteDataService(): DataService {
  return {
    init: notImplemented('init'),
    reset: notImplemented('reset'),
    auth: {
      signIn: notImplemented('auth.signIn'),
      signUp: notImplemented('auth.signUp'),
      requestPasswordReset: notImplemented('auth.requestPasswordReset'),
      verifyPasswordResetCode: notImplemented('auth.verifyPasswordResetCode'),
      resetPassword: notImplemented('auth.resetPassword'),
    },
    lookups: {
      list: notImplemented('lookups.list'),
      create: notImplemented('lookups.create'),
      update: notImplemented('lookups.update'),
      remove: notImplemented('lookups.remove'),
      listForMaintenance: notImplemented('lookups.listForMaintenance'),
      listCouncilSpecific: notImplemented('lookups.listCouncilSpecific'),
      saveCouncilSpecific: notImplemented('lookups.saveCouncilSpecific'),
      removeCouncilSpecific: notImplemented('lookups.removeCouncilSpecific'),
    },
    councils: {
      list: notImplemented('councils.list'),
      get: notImplemented('councils.get'),
      listAffiliated: notImplemented('councils.listAffiliated'),
      create: notImplemented('councils.create'),
      update: notImplemented('councils.update'),
      remove: notImplemented('councils.remove'),
      setFeatureFlags: notImplemented('councils.setFeatureFlags'),
      setBylaws: notImplemented('councils.setBylaws'),
      setDuesRate: notImplemented('councils.setDuesRate'),
      setGlobalParameters: notImplemented('councils.setGlobalParameters'),
      setRankThresholds: notImplemented('councils.setRankThresholds'),
      setEmailGateway: notImplemented('councils.setEmailGateway'),
    },
    parishes: {
      listByCouncil: notImplemented('parishes.listByCouncil'),
      get: notImplemented('parishes.get'),
      create: notImplemented('parishes.create'),
      update: notImplemented('parishes.update'),
      remove: notImplemented('parishes.remove'),
    },
    pastors: {
      listByParish: notImplemented('pastors.listByParish'),
      listByCouncil: notImplemented('pastors.listByCouncil'),
      create: notImplemented('pastors.create'),
      update: notImplemented('pastors.update'),
      remove: notImplemented('pastors.remove'),
    },
    activities: {
      listByCouncil: notImplemented('activities.listByCouncil'),
      get: notImplemented('activities.get'),
      create: notImplemented('activities.create'),
      update: notImplemented('activities.update'),
      remove: notImplemented('activities.remove'),
      listSummaries: notImplemented('activities.listSummaries'),
    },
    distributionLists: {
      listByCouncil: notImplemented('distributionLists.listByCouncil'),
      listForMember: notImplemented('distributionLists.listForMember'),
      create: notImplemented('distributionLists.create'),
      update: notImplemented('distributionLists.update'),
      remove: notImplemented('distributionLists.remove'),
    },
    members: {
      get: notImplemented('members.get'),
      getByEmail: notImplemented('members.getByEmail'),
      listByCouncil: notImplemented('members.listByCouncil'),
      listRoles: notImplemented('members.listRoles'),
      create: notImplemented('members.create'),
      update: notImplemented('members.update'),
      resendWelcome: notImplemented('members.resendWelcome'),
      sweepInactive: notImplemented('members.sweepInactive'),
      listAffiliations: notImplemented('members.listAffiliations'),
    },
    memberProfiles: {
      listOptions: notImplemented('memberProfiles.listOptions'),
      getExtensions: notImplemented('memberProfiles.getExtensions'),
      updateExtensions: notImplemented('memberProfiles.updateExtensions'),
    },
    communication: {
      listCouncilSkills: notImplemented('communication.listCouncilSkills'),
      sendBulkToSkills: notImplemented('communication.sendBulkToSkills'),
    },
    donations: {
      listMethods: notImplemented('donations.listMethods'),
      listAllMethods: notImplemented('donations.listAllMethods'),
      listTypes: notImplemented('donations.listTypes'),
      list: notImplemented('donations.list'),
      listHistory: notImplemented('donations.listHistory'),
      record: notImplemented('donations.record'),
      update: notImplemented('donations.update'),
      remove: notImplemented('donations.remove'),
    },
    expenses: {
      listUserReports: notImplemented('expenses.listUserReports'),
      listCouncilQueue: notImplemented('expenses.listCouncilQueue'),
      listAssetsInventory: notImplemented('expenses.listAssetsInventory'),
      getAssetRecord: notImplemented('expenses.getAssetRecord'),
      getAssetRecordForExpense: notImplemented('expenses.getAssetRecordForExpense'),
      updateAssetRecord: notImplemented('expenses.updateAssetRecord'),
      listAuthorizationQueue: notImplemented('expenses.listAuthorizationQueue'),
      submitReport: notImplemented('expenses.submitReport'),
      rejectReport: notImplemented('expenses.rejectReport'),
      financialSecretaryAuditOrder: notImplemented('expenses.financialSecretaryAuditOrder'),
      treasurerLedgerAudit: notImplemented('expenses.treasurerLedgerAudit'),
      listTreasurerQueue: notImplemented('expenses.listTreasurerQueue'),
      grandKnightAuthorizeOrder: notImplemented('expenses.grandKnightAuthorizeOrder'),
      recordDisbursement: notImplemented('expenses.recordDisbursement'),
    },
    events: {
      get: notImplemented('events.get'),
      getShift: notImplemented('events.getShift'),
      listShiftsBetween: notImplemented('events.listShiftsBetween'),
      listSignups: notImplemented('events.listSignups'),
      signupForShift: notImplemented('events.signupForShift'),
      listMemberShifts: notImplemented('events.listMemberShifts'),
      listShiftFeed: notImplemented('events.listShiftFeed'),
      countNoShows: notImplemented('events.countNoShows'),
      setNoShow: notImplemented('events.setNoShow'),
      listCalendarRange: notImplemented('events.listCalendarRange'),
      uploadPhotos: notImplemented('events.uploadPhotos'),
      setFlyerFile: notImplemented('events.setFlyerFile'),
      listByCouncil: notImplemented('events.listByCouncil'),
      listShifts: notImplemented('events.listShifts'),
      listTurnout: notImplemented('events.listTurnout'),
      listCouncilIds: notImplemented('events.listCouncilIds'),
      create: notImplemented('events.create'),
      update: notImplemented('events.update'),
      setCouncils: notImplemented('events.setCouncils'),
      copy: notImplemented('events.copy'),
      createShift: notImplemented('events.createShift'),
      updateShift: notImplemented('events.updateShift'),
      deleteShift: notImplemented('events.deleteShift'),
      setIntakeSessionStatus: notImplemented('events.setIntakeSessionStatus'),
      listPlanningTime: notImplemented('events.listPlanningTime'),
      logPlanningTime: notImplemented('events.logPlanningTime'),
      deletePlanningTime: notImplemented('events.deletePlanningTime'),
    },
    lessonsLearned: {
      list: notImplemented('lessonsLearned.list'),
      add: notImplemented('lessonsLearned.add'),
      remove: notImplemented('lessonsLearned.remove'),
      listGlobalRegistry: notImplemented('lessonsLearned.listGlobalRegistry'),
    },
    eventTime: { logHours: notImplemented('eventTime.logHours') },
    activityTime: {
      logHours: notImplemented('activityTime.logHours'),
      addQuarterHour: notImplemented('activityTime.addQuarterHour'),
      listByActivity: notImplemented('activityTime.listByActivity'),
    },
    reports: {
      monthlySummary: notImplemented('reports.monthlySummary'),
      missionAreaFootprint: notImplemented('reports.missionAreaFootprint'),
      listNoShowsAudit: notImplemented('reports.listNoShowsAudit'),
      listShiftsAwaitingHours: notImplemented('reports.listShiftsAwaitingHours'),
      councilEngagement: notImplemented('reports.councilEngagement'),
      memberCenter: notImplemented('reports.memberCenter'),
    },
    meetings: {
      get: notImplemented('meetings.get'),
      listUpcoming: notImplemented('meetings.listUpcoming'),
      listSchedules: notImplemented('meetings.listSchedules'),
      create: notImplemented('meetings.create'),
      listInvites: notImplemented('meetings.listInvites'),
      invite: notImplemented('meetings.invite'),
      setAttended: notImplemented('meetings.setAttended'),
      setMinutes: notImplemented('meetings.setMinutes'),
      linkGoogleDrive: notImplemented('meetings.linkGoogleDrive'),
      memberHours: notImplemented('meetings.memberHours'),
      listCouncilMeetingTypes: notImplemented('meetings.listCouncilMeetingTypes'),
      rsvpToInvite: notImplemented('meetings.rsvpToInvite'),
      getAgendaTemplate: notImplemented('meetings.getAgendaTemplate'),
      saveAgendaTemplate: notImplemented('meetings.saveAgendaTemplate'),
      populateAnnualCadence: notImplemented('meetings.populateAnnualCadence'),
      listCadenceConfigs: notImplemented('meetings.listCadenceConfigs'),
      saveCadenceConfig: notImplemented('meetings.saveCadenceConfig'),
      removeCadenceConfig: notImplemented('meetings.removeCadenceConfig'),
      listProposedMotions: notImplemented('meetings.listProposedMotions'),
      startLiveAssemblyConsole: notImplemented('meetings.startLiveAssemblyConsole'),
      advanceActiveAgendaItem: notImplemented('meetings.advanceActiveAgendaItem'),
      logLiveAttendanceOverride: notImplemented('meetings.logLiveAttendanceOverride'),
      launchSecretSmartphoneBallot: notImplemented('meetings.launchSecretSmartphoneBallot'),
      castAnonymousMobileVote: notImplemented('meetings.castAnonymousMobileVote'),
      finalizeProposedMotionVote: notImplemented('meetings.finalizeProposedMotionVote'),
      getLiveAssemblyState: notImplemented('meetings.getLiveAssemblyState'),
      closeLiveAssemblyConsole: notImplemented('meetings.closeLiveAssemblyConsole'),
      getMeetingAgenda: notImplemented('meetings.getMeetingAgenda'),
      applyAgendaBlueprint: notImplemented('meetings.applyAgendaBlueprint'),
      editAgendaLine: notImplemented('meetings.editAgendaLine'),
      addAgendaLine: notImplemented('meetings.addAgendaLine'),
      recordHandBallotTally: notImplemented('meetings.recordHandBallotTally'),
      linkHandTallyTransaction: notImplemented('meetings.linkHandTallyTransaction'),
    },
    shifts: { getShiftDefaultLength: notImplemented('shifts.getShiftDefaultLength') },
    notifications: {
      registerDeviceToken: notImplemented('notifications.registerDeviceToken'),
      listMemberAlerts: notImplemented('notifications.listMemberAlerts'),
      markAsRead: notImplemented('notifications.markAsRead'),
      dispatchHighPriorityAlert: notImplemented('notifications.dispatchHighPriorityAlert'),
    },
    elections: {
      listOfficerSeats: notImplemented('elections.listOfficerSeats'),
      listBallotConfig: notImplemented('elections.listBallotConfig'),
      listVacancies: notImplemented('elections.listVacancies'),
      toggleRoleBallotStatus: notImplemented('elections.toggleRoleBallotStatus'),
      submitNomination: notImplemented('elections.submitNomination'),
      recordOfficerAbdication: notImplemented('elections.recordOfficerAbdication'),
      assignAppointedRole: notImplemented('elections.assignAppointedRole'),
      concludeFraternalYear: notImplemented('elections.concludeFraternalYear'),
    },
    charities: {
      searchGlobalRegistry: notImplemented('charities.searchGlobalRegistry'),
      listSuggestedLocal: notImplemented('charities.listSuggestedLocal'),
      connectCouncilToCharity: notImplemented('charities.connectCouncilToCharity'),
      proposeDonation: notImplemented('charities.proposeDonation'),
      addGlobalCharity: notImplemented('charities.addGlobalCharity'),
      hydrateAndDisburse: notImplemented('charities.hydrateAndDisburse'),
      listMyProposals: notImplemented('charities.listMyProposals'),
      listCouncilProposals: notImplemented('charities.listCouncilProposals'),
      listCouncilLedger: notImplemented('charities.listCouncilLedger'),
      rejectProposal: notImplemented('charities.rejectProposal'),
      listCouncilRelationshipTypes: notImplemented('charities.listCouncilRelationshipTypes'),
      listCouncilMissionAreas: notImplemented('charities.listCouncilMissionAreas'),
      listCharitableRequestsQueue: notImplemented('charities.listCharitableRequestsQueue'),
      submitCharitableRequest: notImplemented('charities.submitCharitableRequest'),
      listMyCharitableRequests: notImplemented('charities.listMyCharitableRequests'),
      triageRequestStatus: notImplemented('charities.triageRequestStatus'),
      routeRequestToNextEligibleAgenda: notImplemented('charities.routeRequestToNextEligibleAgenda'),
      listApprovedFundingQueue: notImplemented('charities.listApprovedFundingQueue'),
      listLinkableCharitableRequests: notImplemented('charities.listLinkableCharitableRequests'),
      listRequestThreads: notImplemented('charities.listRequestThreads'),
      openRequestThread: notImplemented('charities.openRequestThread'),
      postRequestThreadMessage: notImplemented('charities.postRequestThreadMessage'),
    },
    budget: {
      listAnnualForecast: notImplemented('budget.listAnnualForecast'),
      updateLineItemBudget: notImplemented('budget.updateLineItemBudget'),
      addCustomBudgetLine: notImplemented('budget.addCustomBudgetLine'),
      prePopulateNextYear: notImplemented('budget.prePopulateNextYear'),
      approveAndFinalizeEntireBudget: notImplemented('budget.approveAndFinalizeEntireBudget'),
      getBudgetProgress: notImplemented('budget.getBudgetProgress'),
      getHistoricalKPIs: notImplemented('budget.getHistoricalKPIs'),
      getConcludedPerformance: notImplemented('budget.getConcludedPerformance'),
      setLineQuantityAndUnitCost: notImplemented('budget.setLineQuantityAndUnitCost'),
      amendApprovedLine: notImplemented('budget.amendApprovedLine'),
      listLineVersions: notImplemented('budget.listLineVersions'),
      getPriorYearBaselines: notImplemented('budget.getPriorYearBaselines'),
      getBudgetAnalysis: notImplemented('budget.getBudgetAnalysis'),
      setTargetSpendingCeiling: notImplemented('budget.setTargetSpendingCeiling'),
    },
    finance: {
      listChartOfAccounts: notImplemented('finance.listChartOfAccounts'),
      logDoubleEntryTransaction: notImplemented('finance.logDoubleEntryTransaction'),
      logConcludedRevenue: notImplemented('finance.logConcludedRevenue'),
      transferAssetFunds: notImplemented('finance.transferAssetFunds'),
      getLatestBalanceSheet: notImplemented('finance.getLatestBalanceSheet'),
      getAccountLedger: notImplemented('finance.getAccountLedger'),
      listLedgerTransactions: notImplemented('finance.listLedgerTransactions'),
      uploadBankStatementReconciliation: notImplemented('finance.uploadBankStatementReconciliation'),
      getCouncilNetWorth: notImplemented('finance.getCouncilNetWorth'),
      listTrusteeAudits: notImplemented('finance.listTrusteeAudits'),
      getTrusteeAudit: notImplemented('finance.getTrusteeAudit'),
      setAuditLineVerified: notImplemented('finance.setAuditLineVerified'),
      signTrusteeAudit: notImplemented('finance.signTrusteeAudit'),
    },
    supreme: {
      previewReport: notImplemented('supreme.previewReport'),
      syncAlchemerReport: notImplemented('supreme.syncAlchemerReport'),
      listSyncHistory: notImplemented('supreme.listSyncHistory'),
      syncSupremeRoster: notImplemented('supreme.syncSupremeRoster'),
    },
    history: {
      getLegacyMatrix: notImplemented('history.getLegacyMatrix'),
      saveYearAnnals: notImplemented('history.saveYearAnnals'),
      addDiaryEntry: notImplemented('history.addDiaryEntry'),
      getInMemoriamRoll: notImplemented('history.getInMemoriamRoll'),
      saveInMemoriamEntry: notImplemented('history.saveInMemoriamEntry'),
      compileInMemoriam: notImplemented('history.compileInMemoriam'),
      listLeadershipSnapshots: notImplemented('history.listLeadershipSnapshots'),
    },
    media: {
      getLibrary: notImplemented('media.getLibrary'),
      uploadToVault: notImplemented('media.uploadToVault'),
      listSmartAlbums: notImplemented('media.listSmartAlbums'),
      saveSmartAlbum: notImplemented('media.saveSmartAlbum'),
      deleteSmartAlbum: notImplemented('media.deleteSmartAlbum'),
    },
    prayers: {
      getBoard: notImplemented('prayers.getBoard'),
      addIntention: notImplemented('prayers.addIntention'),
      pray: notImplemented('prayers.pray'),
      closeIntention: notImplemented('prayers.closeIntention'),
    },
    devotionals: {
      getProgress: notImplemented('devotionals.getProgress'),
      record: notImplemented('devotionals.record'),
    },
    feedback: {
      submit: notImplemented('feedback.submit'),
      listInbox: notImplemented('feedback.listInbox'),
    },
    messages: {
      getPage: notImplemented('messages.getPage'),
      createReadReceiptStubs: notImplemented('messages.createReadReceiptStubs'),
      listThreads: notImplemented('messages.listThreads'),
      listThread: notImplemented('messages.listThread'),
      send: notImplemented('messages.send'),
      saveDraft: notImplemented('messages.saveDraft'),
      deleteDraft: notImplemented('messages.deleteDraft'),
      setRead: notImplemented('messages.setRead'),
    },
  };
}
